#include <stdio.h>
int main()
{ struct vendedor
		{ int codigo_vendedor, mes;
			char nome_vendedor[20];
			float valor_venda;
		};
	FILE *loja, *auxi;
	vendedor b;
	int cod, mes, c;
	loja = fopen("c:\\vendas.dat", "ab+");

	if (loja == NULL)
	   { printf("\nErro na criacao do arquivo");
		 getchar();
	   }
	else
	   { printf("Digite o codigo do vendedor a ser excluido: ");
         scanf("%d%*c", &cod);
         printf("Digite o mes a ser excluido: ");
         scanf("%d%*c", &mes);
         c=0;
		 fread(&b, sizeof(vendedor), 1, loja);
		 while ((!feof(loja)) && ((cod != b.codigo_vendedor) || (mes != b.mes)))
		   { fread(&b, sizeof(vendedor), 1, loja);
		     c++;
		   }
		 if (feof(loja))
			{ printf("\nVenda nao cadastrada ! ");
		      getchar();
			  fclose(loja);
			}
		 else
			{ auxi = fopen("c:\\auxi.dat", "ab+");
		      fclose(loja);
			  loja = fopen("c:\\vendas.dat", "rb");
			  fread(&b, sizeof(vendedor), 1, loja);
			  while (!feof(loja))
				{ if ((b.codigo_vendedor != cod) || (b.mes != mes))
					 fwrite(&b, sizeof(vendedor), 1, auxi);
			      fread(&b, sizeof(vendedor), 1, loja);
				}
			 fclose(loja);
			 fclose(auxi);
			 remove("c:\\vendas.dat");
			 rename("c:\\auxi.dat", "c:\\vendas.dat");
			 printf("\nDados exclu¡dos com sucesso !");
			 getchar();
		   }
	  }
 return 0;
}
